spring:
  application:
    name: Authentication
  datasource:
    url: jdbc:postgresql://localhost:5432/ned_authentication
    username: ned_user_db
    password: ned_pass_db
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    validate-on-migrate: true
ned:
  vars:
    SECRET_KEY: ""
server:
  port: 8090
