spring:
  application:
    name: Authentication
  datasource:
    url: jdbc:postgresql://localhost:5432/ned_authentication
    username: ned_user_db
    password: ned_pass_db
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    validate-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "q4HFI4SiP1rCInbAgHdMA2/O4RuogyIyda2ungWB035/mN5rwp2tndN4VeoVIuTgP007X6Xq0CXjAAQNZ8JGkw=="

NED:
  security:
    jwt:
      config:
        issuer: "NED"
        expires_in_seconds: "3600"

server:
  port: 8090
